### PR TITLE
[BUGFIX] Fix embedding of images

### PR DESCRIPTION
**Pull request by tobenschmidt**
Remove usage of method mime_content_type which does not work with basename($media['absRef'] as argument. Instead use API method embed to embed images with Content-ID standard.

### CODE REVIEW

**Comment by AnatoliZich** [comment]
I take a look sometime this week. 
This is odd though. I also tried the ContentID functionality but could not get it to work. 

The `mime_content_type` method builds the mime type by the filename string alone, so im curious what kind of files you try to embed. Could you provide some examples?

**Comment by tobenschmidt** [comment]
In my development system `mime_content_type` leads to an PHP warning in the moment I manually invoke the mailer engine:

> (1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
> 
> PHP Warning: mime_content_type(my_image_file.png): failed to open stream: No such file or directory in /foo/bar/baz/public/typo3conf/ext/direct_mail/Classes/Dmailer.php line 916

I tried a few things until I finally managed to embed the image with Content-ID via API-call `embed`. This is the related source code of an example mail:

Image tag:
``

Header of embedded image:
> Content-ID: <d3109b8dju734a96c1008f126a0e00cb@symfony>
> Content-Type: application/octet-stream; name=my_image_file.png
> Content-Transfer-Encoding: base64
> Content-Disposition: inline; name=my_image_file.png;
> filename=my_image_file.png

In my case this solution works in Mozilla Thunderbird und Nextcloud's mail app RainLoop.

I tried to set the value of Content-Type according to the image file but this seems to be impossible with `embed`. 

(Sorry for the late response. Been on vacation the last weeks.)

**Comment by tobenschmidt** [comment]
Just created a pull request for this at kartolo/direct_mail#220.

**Comment by AnatoliZich** [comment]
Im sorry for the late answer. Since my branch was merged into the original package, this should indeed be merged there to avoid a real fork. Thank you for caring though 👍

**Pull request closed without merging**
